# Generated by Django 3.2.4 on 2022-12-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userType',
            field=models.CharField(choices=[('1', 'Store manager'), ('2', 'Store Employee'), ('3', 'admin')], default='1', max_length=20),
        ),
    ]
