# Generated by Django 3.2.4 on 2022-12-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_userprofile_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='aboutMe',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='myGoal',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.CharField(choices=[('1', 'Store manager'), ('2', 'Store Employee'), ('3', 'Store Admin')], default='1', max_length=20),
        ),
    ]
