# Generated by Django 3.2.4 on 2022-12-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20221208_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Email',
            new_name='email',
        ),
    ]
