# Generated by Django 3.2.4 on 2023-01-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_rename_email_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('supplier', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
