# Generated by Django 3.2.4 on 2023-01-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_suppliers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='supplier',
            new_name='supplier_name',
        ),
    ]
