# Generated by Django 3.2.4 on 2023-01-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_rename_supplier_products_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
