# Generated by Django 3.2.4 on 2023-01-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delivery_name', models.CharField(max_length=32)),
                ('total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('order_date', models.DateTimeField(null=True)),
                ('delivery_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=32)),
                ('Products', models.ManyToManyField(related_name='products', to='mainApp.Products')),
            ],
        ),
    ]
