# Generated by Django 3.2.4 on 2023-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='Supplier_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
