# Generated by Django 3.2.4 on 2023-02-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_suppliers_supplier_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Delivery_name',
            new_name='delivery_name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='total',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Products',
        ),
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='mainApp.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.CharField(choices=[('1', 'Store manager'), ('2', 'Store Employee')], default='1', max_length=20),
        ),
    ]
