# Generated by Django 3.2.4 on 2023-02-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_alter_orders_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliers',
            old_name='Supplier_email',
            new_name='SupplierEmail',
        ),
    ]
